name: Update Stats

on:
  workflow_dispatch:
  repository_dispatch:
    types: [update_stats]

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Update stats.json
        run: |
          echo "Получаем входные данные"
          VISITS=${{ github.event.client_payload.visits }}
          LIKES=${{ github.event.client_payload.likes }}

          echo "Обновляем stats.json"
          jq --arg v "$VISITS" --arg l "$LIKES" \
            '.visits = ($v | tonumber) | .likes = ($l | tonumber)' \
            stats.json > new.json

          mv new.json stats.json

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto Update Stats"
